# Summary of Theory

## Defining atomic charge

The charge definition we use is our primitive Hirshfeld-I method, defined in full in the Supplementary Theory.
As in the original Hirshfeld-I method, electron populations $N_k$ are defined as integrals of a weight function $\weightFunc{k}{\vect{N}}$ against the density function, where the weight function depends on both the element and on the electron populations of each atom:
\begin{equation}
N_k = \spaceIntegral{\weightFunc{k}{\vect{N}} \, \electronDensityValue}
(\#eq:AtomicPopulationSummary)
\end{equation}
The charge is then
\begin{equation}
q_k = Z_k - N_k
(\#eq:AtomicChargeSummary)
\end{equation}
where $Z_k$ is the atomic number.

## Defining atomic electronegativity

To define electronegativities, we consider the energy $\energyNuc$ (defined formally in the Supplementary Theory), which includes the Coulomb potential of the nuclei but not the imposed potential.
The electronegativities are
\begin{equation}
\chi_D = \constDeriv{\energyNuc}{q_D}{q_A} \qquad \chi_A = \constDeriv{\energyNuc}{q_A}{q_D}
(\#eq:ChiDefSummary)
\end{equation}

In conceptual DFT, electronegativity is a derivative at fixed potential [@parrcdftelectronegativity].
We do not notate the constant potential, but we enforce this constraint by defining electronegativity in terms of $\energyNuc$, which excludes the varying imposed potential.

In our simulations we will smoothly vary the imposed potential while the total electron number $N$ stays constant, so within our series of simulations the derivative of $\energyNuc$ will be
\begin{equation}
\constDeriv{\energyNuc}{q_A}{N} = \chi_A - \chi_D = \Delta \chi
(\#eq:EnergyDerivativeDeltaChiSummary)
\end{equation}

The derivative of the energy of a system with respect to its electron population is piecewise linear [@piecewiseLinearEnergy].
However, the derivative in Equation \@ref(eq:EnergyDerivativeDeltaChiSummary) describes charge transfer within a system of fixed total electron population, and will not be piecewise linear.

## Measuring atomic electronegativity

We will measure atomic electronegativities $\chi_k$ by performing DFT simulations with an additional potential imposed.
Since $\chi_k$ is the negative of a chemical potential, the underlying principle is measuring an "internal" chemical potential with an "external" potential imposed on the system, in the terminology of @kittel1980thermal.

In order to relate the imposed potential to atomic electronegativities, the field must have a form defined by the weight functions from the charge definition in equation \@ref(eq:AtomicPopulationSummary).
\begin{equation}
\imposedPotentialValue{} = \sum_k \lambda_k \, \weightFunc{k}{\vect{N}}
(\#eq:ElectricalPotentialSummary)
\end{equation}

Our simulations will be of systems of two atoms, which we refer to as a donor atom $D$ and an acceptor atom $A$.
We impose a shaped potential such that $\lambda_A = -\lambda_D = \lambda$ so that
\begin{equation}
\imposedPotentialValue{} = \lambda \, \weightFunc{A}{N_D, N_A} - \lambda \, \weightFunc{D}{N_D, N_A}
(\#eq:TwoAtomPotentialSummary)
\end{equation}
$\lambda$ can be taken as a measure of the strength of the imposed potential.
This potential is positive on the acceptor to push electron density back onto the donor, but interpreted it as an electrical potential, it is electrically negative on the acceptor to repel electrons back to the donor.

To measure $\Delta \chi$, we rely on a relationship with the strength of the field applied to each atom.
In the Supplementary Theory, we show the derivation of the relationship for an arbitrary number of atoms, and an arbitrary vector of field coefficients $\lambda_k$.
For two atoms and specific form of the field, it simplifies considerably.
If the weight functions did not depend on the electron populations, the relationship would be
\begin{equation}
\Delta \chi = 2 \, \lambda
(\#eq:DeltaChiNoBoundarySummary)
\end{equation}
That is, the difference in electronegativity could be read off simply from the field that was used as input to the simulation.
Including the shift in the definition of atoms requires another factor in this relationship:
\begin{equation}
\Delta \chi = 2\,\left( 1 - \avgWeightDerivSubscript{A}{A}{N} \right)\lambda
(\#eq:DeltaChiWithBoundarySummary)
\end{equation}
where $\avgWeightDerivSubscript{A}{A}{N}$ is the derivative of the weight function integrated against the electron density, discussed in more detail in the Supplementary Theory.
We evaluate this constant by numerical integration.

<!-- Constrained density functional theory -->
In constrained density functional theory, the penalty term enforcing the charge constraint can be interpreted as a potential of the form in Equation \@ref(eq:ElectricalPotentialSummary), and Equation \@ref(eq:DeltaChiNoBoundarySummary) follows from a "thermodynamic relation" between the Lagrange multiplier and the chemical potential [@KadukConstrainedDFTReview].
From this perspective, the electronegativity is a derivative of the energy with respect to a constraint.
This makes it a "generalized force" in the terminology of @thermo-dynamics.

## Predictive model

The linear model underlying QEq, in the two-atom case excluding the Coulomb interaction term, is
\begin{equation}
\widehat{\Delta \chi} = \chi_{e(A)}^0 - \chi_{e(D)}^0 + \eta_{e(A)} \, q_A + \eta_{e(D)} \, q_D
(\#eq:QEqLinearModelSummary)
\end{equation}
where $\widehat{\Delta \chi}$ is the estimated value of $\Delta \chi$ using these model parameters.
The estimate of charge is obtained by electronegativity equalization, that is, setting $\widehat{\Delta \chi}=0$ and $q_D+q_A=0$ in Equation \@ref(eq:QEqLinearModelSummary), which after solving for $q_A$ yields
\begin{equation}
-\hat{q}_A = \frac{\chi_{e(A)}^0 - \chi_{e(D)}^0}{\eta_{e(A)} + \eta_{e(D)}}
(\#eq:ChargeEstimateSummary)
\end{equation}
This is the familiar electronegativity equalization formula for charge transfer between two fragments [@electronegativityEqualizationInorganic].

<!-- Locality of the electronegativity difference, in contrast to the charge transfer -->
One of the selling points of QEq over using ML to predict charge directly has been that the $\chi^0_k$ values are apparently more local than the charges $q_k$ [@Ko2021].
The locality of $\chi_k$, in contrast to $q_k$, is indicated by contrasting equation \@ref(eq:ChargeEstimateSummary) for $\hat{q}_A$ with equation \@ref(eq:QEqLinearModelSummary) for $\widehat{\Delta \chi}$.
$\hat{q}_A$ is a linear function of $\chi_{e(A)}^0$ and $\chi_{e(D)}^0$, but the coefficients in this linear equation mix the hardnesses of both atoms.
In contrast, $\widehat{\Delta \chi}$ is a linear function of $q_A$ and $q_D$, but the coefficient on the charge of an atom depends on the hardness of that atom only.
Conceptually, estimating charge requires taking into account every atom that is competing for the fixed pool of charge.

The sensitivity of the charge predictions to error in the model parameters can be computed by differentiating the electronegativity equalization equation \@ref(eq:ChargeEstimateSummary) with respect to the model parameters, showing that the higher the hardnesses, the less the error propagates.

## Loss function for training the model

We train the model by minimizing the loss function
\begin{equation}
\sum_i \left(\smash[t]{\widehat{\Delta \chi}}^{(i)} - \smash[t]{\Delta \chi}^{(i)} \right)^2
(\#eq:DeltaChiLossSqSummary)
\end{equation}
using the predictions $\widehat{\Delta \chi}$ given in Equation \@ref(eq:QEqLinearModelSummary) and the $\Delta \chi$ values extracted from the simulation using the relationship with the potentials in Equation \@ref(eq:DeltaChiWithBoundarySummary).

<!-- Hohenberg-Kohn map -->
It is worth noting that since the $q_k$ are computed from the electron density and the $\lambda_k$ parametrize the potential, the $\chi$-prediction task requires learning a map from the density to the potential.
In this case it is a crude map that throws away most of the information in the density, but the first Hohenberg-Kohn theorem guarantees the existence of an exact map from density to potential [@hohenbergKohn].
