# Supplementary theory

## Functional derivative of energy

We will probe electronegativity by imposing an external electric field that adds a potential $\imposedPotential$.
Let $\energyTot$ be the energy of the ground state in this potential.
It is stationary with respect to variations in the density:

\begin{equation}
  \funcDerivValue{\energyTot}{\electronDensity} = \mu
  (\#eq:StationaryCondition)
\end{equation}

where $\mu$ is the chemical potential.

In the conceptual DFT definition [@parrcdftelectronegativity], the electronegativity is defined as the negative of the chemical potential:
\begin{equation}
  \chi = -\mu.
  (\#eq:ChiDef)
\end{equation}
However, we will continue to work with chemical potentials for theoretical derivations, for consistency with previous publications, and only flip signs as required in final results.

Let $\energyNuc$ be the energy of the same state, but considering only the potential of the nuclei.
Then,

\begin{equation}
  \funcDerivValue{\energyTot}{\electronDensity}
    = \funcDerivValue{\energyNuc}{\electronDensity} + \imposedPotentialValue
  (\#eq:EnergySplit)
\end{equation}

Combining Equations \@ref(eq:StationaryCondition) and \@ref(eq:EnergySplit) yields a relationship between the functional derivative of $\energyNuc$ and the imposed potential:

\begin{equation}
  \funcDerivValue{\energyNuc}{\electronDensity}
    = \mu - \imposedPotentialValue
  (\#eq:RelateNucPotential)
\end{equation}

The negative of $\funcDerivValue{\energyNuc}{\electronDensity}$ is like an electronegativity of a point in space.

## Definition of atomic electron populations and charges

To transition to considering individual atoms, we will begin with a definition of the electron population $N_k$ of atom $k$ in terms of a weight function $\weightFunc{k}{\vect{N}}$:

\begin{equation}
  N_k = \spaceIntegral{\weightFunc{k}{\vect{N}} \electronDensityValue}
  (\#eq:AtomicPopulation)
\end{equation}

These weights add to 1 at each point:
\begin{equation}
  \sum_{k} \weightFunc{k}{\vect{N}} = 1
  (\#eq:PartitionUnity)
\end{equation}

This implies an intuitive relation, which will be required later:
\begin{equation}
  dN = \sum_{k} \popChange{k},
  (\#eq:TotalPopChange)
\end{equation}

For these derivations, we will work with atomic electron populations, but for the final formulas, we will substitute to obtain atomic partial charges:
\begin{equation}
  q_k = Z_k - N_k
  (\#eq:AtomicCharge)
\end{equation}
where $Z_k$ is the nuclear charge of atom $k$.

## Definition of atomic electronegativity

Following the approach of conceptual density functional theory, the electronegativity of an atom will be defined in terms of the chemical potential.
The chemical potential of an atom will be defined as the derivative of the energy of the system (considering only the potential of the nuclei) with respect to the electron population of that atom, while holding the electron populations of all other atoms constant:

\begin{equation}
  \mu_k
    = \constDeriv{\energyNuc}{N_k}{N_1,\cdots,N_{k-1},N_{k+1},\cdots}
  (\#eq:ChemicalPotentialDef)
\end{equation}

The total differential:

\begin{equation}
  d\energyNuc
    = \sum_{k} \mu_k \popChange{k}
  (\#eq:ChemicalPotentialsTotalDifferential)
\end{equation}

Atomic electronegativity is $\chi_k = - \mu_k$.
Equivalently, in terms of charge,
\begin{equation}
  \chi_k
    = \constDeriv{\energyNuc}{q_k}{q_1,\cdots,q_{k-1},q_{k+1},\cdots}
  (\#eq:AtomicElectronegativityDef)
\end{equation}

## Measuring atomic electronegativity by imposing a potential

In order to obtain a relationship between the atomic chemical potential and the imposed potential analogous to Equation \@ref(eq:RelateNucPotential), we will also require that the imposed potential has a shape defined by the weight functions:

\begin{equation}
  \imposedPotentialValue
    = \sum_{k} \lambda_k \weightFunc{k}{\vect{N}}
  (\#eq:ImposedPotential)
\end{equation}

As in the fixed weight function special case, substituting Equation \@ref(eq:ImposedPotential) into Equation \@ref(eq:RelateNucPotential) gives

\begin{equation}
  \funcDerivValue{\energyNuc}{\electronDensity}
    = \mu - \sum_{k} \lambda_k \weightFunc{k}{\vect{N}}
  (\#eq:FuncDerivWithWeights)
\end{equation}

Then, considering a change in energy $d\energyNuc$ associated with a density variation $\delta\electronDensityValue$:

\begin{equation}
  d\energyNuc
    = \spaceIntegral{\funcDerivValue{\energyNuc}{\electronDensity} \delta\electronDensityValue}
  (\#eq:EnergyNucVariation)
\end{equation}

Substituting Equation \@ref(eq:FuncDerivWithWeights) into Equation \@ref(eq:EnergyNucVariation) and rearranging, we obtain the total differential:

\begin{equation}
  d\energyNuc
    = \mu dN - \sum_{k} \lambda_k \popChangeFixed{k}
  (\#eq:ThermoRelationConstant)
\end{equation}
where $dN$ is the total change in electron count:
\begin{equation}
  dN = \spaceIntegral{\delta\electronDensityValue}
  (\#eq:TotalElectronChange)
\end{equation}
and $\popChangeFixed{k}$ is the change in electron population of atom $k$ while holding the weight function fixed:
\begin{equation}
  \popChangeFixed{k}
    = \spaceIntegral{\weightFunc{k}{\vect{N}} \delta\electronDensityValue}
  (\#eq:PopChangeFixedK)
\end{equation}

### Special case: fixed weight functions

If these are Hirshfeld weight functions, then we have:

\begin{equation}
  \popChangeFixed{k} = \popChange{k}
  (\#eq:FixedWeightPopChange)
\end{equation}

This enables substituting out $\popChangeFixed{k}$ in Equation \@ref(eq:ThermoRelationConstant).
To also substitute out $dN$, we use equation \@ref(eq:TotalPopChange).
These substitutions yield:
\begin{equation}
  d\energyNuc
    = \sum_{k}
      \left(
        \mu - \lambda_k
      \right)
      \popChange{k}.
  (\#eq:ThermoRelationFixedWeights)
\end{equation}

Relating to the total differential in Equation \@ref(eq:ChemicalPotentialsTotalDifferential) yields
\begin{equation}
  \mu_k
    = \mu - \lambda_k.
  (\#eq:MuKFixedWeights)
\end{equation}

This is all that is required for a constant weight function such as in the original Hirshfeld method, and is typically referred to as a "thermodynamic relation" in the context of constrained DFT [@KadukConstrainedDFTReview].

Flipping the sign, we obtain the relationship between the atomic electronegativities and the imposed field:

\begin{equation}
  \chi_k
    = \chi + \lambda_k.
  (\#eq:ChiKFixedWeights)
\end{equation}

### Accounting for the shift in the atom boundary

When $\weightFunc{k}{\vect{N}}$ depends on the set of populations \(\{N_j\}\), the change in \(N_k\) contains both the change in the electron density and in the atom boundaries:
\begin{equation}
  \popChange{k}
    = \popChangeFixed{k}
      + \spaceIntegral{ \delta \weightFunc{k}{\vect{N}} \electronDensityValue }.
  (\#eq:PopChangeSplit)
\end{equation}
To first order in the population increments,
\begin{equation}
  \delta \weightFunc{k}{\vect{N}}
    = \sum_{j} \weightDerivValue{k}{j}\,\popChange{j}.
  (\#eq:DeltaWkGeneral)
\end{equation}
Though we will not explicitly notate this, these derivatives are assumed to be holding all other atomic populations constant.

Equations \@ref(eq:PopChangeSplit) and \@ref(eq:DeltaWkGeneral) imply
\begin{equation}
  \popChange{k}
  = \popChangeFixed{k}
    + \sum_{j} \avgWeightDeriv{k}{j}\,\popChange{j}.
  (\#eq:PopChangeRelation)
\end{equation}
where
\begin{equation}
  \avgWeightDeriv{k}{j} = \spaceIntegral{ \weightDerivValue{k}{j}\,\electronDensityValue }
  (\#eq:AvgWeightDerivDef)
\end{equation}

Solving for the fixed‑weight population change gives
\begin{equation}
  \popChangeFixed{k}
  = \popChange{k}
    - \sum_{j} \avgWeightDeriv{k}{j}\,\popChange{j}.
  (\#eq:PopChangeFixedFromTotal)
\end{equation}

Substituting Equation \@ref(eq:PopChangeFixedFromTotal) into the general total differential (Equation \@ref(eq:ThermoRelationConstant)) gives
\begin{equation}
\begin{aligned}
  d\energyNuc
    &= \mu dN - \sum_{k} \lambda_k
       \!\left(\popChange{k}
       - \sum_{j} \avgWeightDeriv{k}{j}\,\popChange{j}\right) \\
    &= \mu dN - \sum_{k} \lambda_k\,\popChange{k}
       + \sum_{j}\!\left(\sum_{k} \lambda_k\,\avgWeightDeriv{k}{j}\right)\!\popChange{j}.
\end{aligned}
  (\#eq:SubstitutionExpanded)
\end{equation}
Relabeling dummy indices to collect like terms,
\begin{equation}
  d\energyNuc
  = \mu dN + \sum_{k}
    \left(
      -\lambda_k
      + \sum_{j} \lambda_j\,\avgWeightDeriv{j}{k}
    \right)\popChange{k}.
  (\#eq:CollectBydNk)
\end{equation}
Substituting out $dN$ using Equation \@ref(eq:TotalPopChange) gives
\begin{equation}
    d\energyNuc
    = \sum_{k}
        \left(
        \mu - \lambda_k
        + \sum_{j} \lambda_j\,\avgWeightDeriv{j}{k}
        \right)\popChange{k}.
    (\#eq:MovingBoundaryTotalDifferential)
\end{equation}
Therefore, comparing to the total differential in Equation \@ref(eq:ChemicalPotentialsTotalDifferential), the chemical potentials are
\begin{equation}
  \mu_k
  = \mu - \lambda_k
    + \sum_{j} \lambda_j\,\avgWeightDeriv{j}{k}.
  (\#eq:MuKGeneral)
\end{equation}

Flipping signs to put it in terms of electronegativity:
\begin{equation}
  \chi_k
  = \chi + \lambda_k
    - \sum_{j} \lambda_j\,\avgWeightDeriv{j}{k}.
  (\#eq:ChiKGeneral)
\end{equation}

Since each element is an integral against the density, it is computable from simulation output provided the derivatives \(\weightDerivValue{k}{j}\) can be evaluated.

### Special case for two atoms

Considerable simplification is possible in the case examined in our computational studies, in which there are only two atoms, a donor atom $D$ and an acceptor atom $A$, and the field weights are
\begin{equation}
  \lambda_A = \lambda, \qquad \lambda_D = -\lambda
  (\#eq:TwoAtomFieldStrength)
\end{equation}

The special case of Equation \@ref(eq:PartitionUnity) for two atoms is
\begin{equation}
  \weightFunc{D}{N_D, N_A} + \weightFunc{A}{N_D, N_A} = 1
  (\#eq:TwoAtomPartition)
\end{equation}
and therefore
\begin{equation}
\begin{aligned}
  \weightDerivValue{D}{A} + \weightDerivValue{A}{A} = 0 \\
  \weightDerivValue{D}{D} + \weightDerivValue{A}{D} = 0
\end{aligned}
  (\#eq:TwoAtomWeightSumZero)
\end{equation}

For two atoms, specializing Equation \@ref(eq:MuKGeneral) gives
\begin{equation}
\begin{aligned}
  \mu_D &= \mu -\lambda_D
           + \avgWeightDeriv{D}{D}\lambda_D
           + \avgWeightDeriv{A}{D}\lambda_A \\
  \mu_A &= \mu -\lambda_A
           + \avgWeightDeriv{D}{A}\lambda_D
           + \avgWeightDeriv{A}{A}\lambda_A
\end{aligned}
(\#eq:TwoAtomMu)
\end{equation}

Substituting out $\avgWeightDeriv{D}{D}$ and $\avgWeightDeriv{D}{A}$ with Equation \@ref(eq:TwoAtomWeightSumZero), and $\lambda_D$ and $\lambda_A$ with Equation \@ref(eq:TwoAtomFieldStrength), yields
\begin{equation}
  \mu_D = \mu + \left(1 + 2\,\avgWeightDeriv{A}{D} \right)\lambda,
  \qquad
  \mu_A = \mu - \left(1 - 2\,\avgWeightDeriv{A}{A} \right)\lambda
  (\#eq:TwoAtomMuSimplified)
\end{equation}

Then, the difference of chemical potentials is
\begin{equation}
  \mu_D - \mu_A
  = 2\,\left( 1 + \avgWeightDeriv{A}{D} - \avgWeightDeriv{A}{A} \right)\lambda
  (\#eq:TwoAtomMuDelta)
\end{equation}

A more compact form is possible by restoring the subscripts indicating which variables are held constant.
Then,
\begin{equation}
  \weightDerivSubscript{A}{A}{N} = \weightDerivSubscript{A}{A}{N_D} - \weightDerivSubscript{A}{D}{N_A}
\end{equation}
Integrating,
\begin{equation}
  \avgWeightDerivSubscript{A}{A}{N} = \avgWeightDerivSubscript{A}{A}{N_D} - \avgWeightDerivSubscript{A}{D}{N_A}
\end{equation}

Then, the difference of chemical potentials in equation \@ref(eq:TwoAtomMuDelta) can be written as
\begin{equation}
  \mu_D - \mu_A
  = 2\,\left( 1 - \avgWeightDerivSubscript{A}{A}{N} \right)\lambda
  (\#eq:TwoAtomMuDeltaCompact)
\end{equation}

Reversing signs, this is also the electronegativity difference $\Delta \chi = \chi_A - \chi_D$.

## Linear regression model for atomic electronegativities

The fundamental physical approximation made in charge equilibration models is that the energy is second-order in the atomic partial charges, or equivalently, that the atomic electronegativities are first-order in the charges.
This can be expressed as, for atom $i$ of a system,
\begin{equation}
  \chi_i = \chi_i^0 + \eta_i q_i + \sum_{j \ne i} c_{ij} q_j
  (\#eq:ChiLinearModel)
\end{equation}

$c_{ij}$ is a symmetric ($c_{ij}=c_{ji}$) interaction term, assumed to have some explicit functional form as a function of the distance between the atoms.
Whereas $\chi_i^0$ and $\eta_i$ depend on empirical parameters of the model.

It is not the electronegativities $\chi_i$ that are directly observed, but the field strengths $\lambda_i$ that were imposed. We can express $\chi_i-\chi$ in terms of the field strengths by rearranging Equation \@ref(eq:ChiKGeneral).
\begin{equation}
  \chi_i - \chi
  = \lambda_i - \sum_j \lambda_j\,\avgWeightDeriv{j}{i},
  (\#eq:ChiMinusChiFromLambda)
\end{equation}
The model for this difference is:
\begin{equation}
  \chi_i - \chi
  = -\chi + \chi_i^0 + \eta_i q_i + \sum_{j \ne i} c_{ij} q_j
  (\#eq:LambdaLinearModelAtom)
\end{equation}

Suppose that the $\chi_i^0$ and $\eta_i$ parameters depend only on the element $e$.
Then the equation can be written as:
\begin{equation}
  (\chi_i - \chi) - \sum_{j \ne i} c_{ij} q_j = -\chi + \chi_e^0 + \eta_e q_i
  (\#eq:LambdaLinearModelElement)
\end{equation}
If both charges and field strengths are given, and the interaction term $c_{ij}$ is a known function of interatomic distance which is given, then the left hand side is determined by the data, and is used as the dependent variable in the linear regression model.
And the right hand side is linear in unknown model parameters $\chi_e^0$ and $\eta_e$, and an unknown $\chi$ that is specific to the simulation.
The independent variables of the model are the charges and element indicators.
Collecting each such equation into a linear system, parameters can then be fit with least squares linear regression.

### Special case for two atoms

In this work, we analyze only two-atom systems, which we index as the donor $D$ and the acceptor $A$.
We also assume the interaction term is zero, absorbing interactions into the hardness parameters.
In this case, instead of considering $\chi$ as a variable in the regression as in the general case, an alternative approach is possible.
We instead take as our response the electronegativity differences, which depend on the imposed field and on the weight function derivatives, as described by Equation \@ref(eq:TwoAtomMuDeltaCompact).

Then, for every pair of equations in \@ref(eq:LambdaLinearModelElement), subtracting the donor equation from the acceptor equation yields (assuming $c_{DA}=0$)
\begin{equation}
  \Delta \chi
    = \chi_{eA}^0 - \chi_{eD}^0
      + \eta_{eA} q_A - \eta_{eD} q_D
  (\#eq:DeltaLambdaLinearModel)
\end{equation}
where $eD$ is the donor element and $eA$ is the acceptor element.

### Example

Consider two materials, each simulated at a single field strength, and with the same donor element $e$ but different acceptor elements $f$ and $g$:

\begin{equation}
  \begin{aligned}
    \Delta \chi_1
      &=\chi_{f}^0 - \chi_{e}^0
        + \eta_{f} q_{A1} - \eta_{e} q_{D1} \\
    \Delta \chi_2
      &=\chi_{g}^0 - \chi_{e}^0
        + \eta_{g} q_{A2} - \eta_{e} q_{D2}
  \end{aligned}
  (\#eq:TwoMaterialExampleEquations)
\end{equation}

This can be expressed as a linear system

\begin{equation}
  \begin{pmatrix}
    \Delta \chi_1 \\
    \Delta \chi_2
  \end{pmatrix} =
  \begin{pmatrix}
    -1 & 1 & 0 & -q_{D1} & q_{A1} & 0 \\
    -1 & 0 & 1 & -q_{D2} & 0 & q_{A2}
  \end{pmatrix}
  \begin{pmatrix}
    \chi_{e}^0 \\
    \chi_{f}^0 \\
    \chi_{g}^0 \\
    \eta_{e} \\
    \eta_{f} \\
    \eta_{g}
  \end{pmatrix}
  (\#eq:TwoMaterialExampleLinearSystem)
\end{equation}

This is of the form of a regression problem $y = X \beta$, where $y$ is the dependent variable, $X$ is the design matrix containing the independent variables as columns, and $\beta$ is a vector of parameters to be determined by the regression.

Additional frames of the simulations of these systems with different field strengths add additional rows to this system.
Additional systems add more rows, and also more columns if they involve additional elements.

### Zero of the electronegativity scale in regression

In charge equilibration, electronegativies $\chi^0$ are considered as differences from an arbitrary reference electronegativity.
In the regression framework, this is handled by removing the corresponding column from the design matrix, which is equivalent to setting one of the unknown parameters to zero.

### Primitive Hirshfeld-I

We use a variant of the Hirshfeld-I method, one of a class of methods in which electron populations of atoms are defined as integrals of a weight function:

$$N_k = \spaceIntegral{\weightFunc{k}{\vect{N}} \rho(\position)}$$

In Hirshfeld-I, this weight function is defined as
$$\weightFunc{k}{\vect{N}} = \frac{\rho_k^0(\position; N_k)}{\sum_j \rho_j^0(\position; N_j)}$$
where $\rho_k^0(\position; N_k)$ is called a pro-atom density.

In the original Hirshfeld method, the pro-atom densities did not depend on electron population, and were defined as the electron densities of free atoms.

In the Hirshfeld-I method, these pro-atom densities are linear combinations of densities of free atoms and ions.
The main issue with the Hirshfeld-I method is anions with unbound or nearly unbound electrons, with the nitrogen anion causing particular trouble.

Instead, we define $\rho_k^0(\position; Z_k)$ to be the free neutral atom density, and then
$$\rho_k^0(\position; N_k) = \frac{N_k}{Z_k} \rho_k^0(\position; Z_k)$$
We term the resulting partial charge definition "primitive Hirshfeld-I".

Primitive Hirshfeld-I does not accurately model the changes to the atomic density with charge, but it avoids the issues of Hirshfeld-I with anions.

In fact, due to the limited change in the shape of the pro-atom density, primitive Hirshfeld-I resembles the original Hirshfeld method.
However, unlike the original Hirshfeld method, both Hirshfeld-I and our primitive Hirshfeld-I satisfy the condition
$$N_k = \spaceIntegral{\rho^0_k(\position;N_k)}$$
Since this is the condition that motivated the Hirshfeld-I method, our primitive Hirshfeld-I method is in that sense a member of a broader Hirshfeld-I family.
Primitive Hirshfeld-I is also computed by the same iterative algorithm.
